### PR TITLE
Added other valid line-comment syntaxes

### PR DESCRIPTION
**Pull request by jbtule**
https://harbour.github.io/ng/c53g01c/ngd3e56.html

### CODE REVIEW

**Comment by jbtule** [comment]
Your project is used by github linguist.
https://github.com/github/linguist/tree/master/vendor/grammars

Comments are really useful to have completely implemented.
https://github.com/harbour/core/blob/master/tests/comments.prg

**Comment by APerricone** [comment]
I think you must add `^\s*` in the `line_alt3_comment` also, it is valid only if it is in the beginning of line.

**Comment by hernad** [comment]
@jbtule thank you, sorry for late response

**Comment by hernad** [comment]
@APerricone please try 3.2.1

**Comment by hernad** [comment]
hm, it crashed syntax check completely ...

**Comment by APerricone** [comment]
you need add a space before line_alt2_comment and line_alt3_comment
But the code is not highlighted as comment...

**Pull request merged**
